// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
#if defined(GGML_CUDA_FA_ALL_QUANTS) || !defined(NDEBUG)
DECL_FATTN_VEC_CASE(512, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
#endif
