#!/usr/bin/env python3
"""
Final summary — ties together baseline PPL sweep, KL-divergence, recency-
position split, and NIAH into a single answer about sink/recency
viability for TQ+.

Reads all JSON outputs from bench-tq+/results/ and emits a markdown
summary suitable for the reader's digest.
"""

import argparse
import json
from pathlib import Path


def load_json(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", type=Path, default=Path("bench-tq+/results"))
    ap.add_argument("--out", type=Path, default=Path("bench-tq+/SUMMARY.md"))
    args = ap.parse_args()

    out = []
    out.append("# TQ+ sink/recency investigation — summary of empirical results")
    out.append("")
    out.append("Generated by `bench-tq+/harness/summarize.py`.")
    out.append("")

    # ── PPL sweep ───────────────────────────────────────────────────
    sweep = load_json(args.results_dir / "baseline_c4k_n40.json")
    if sweep:
        out.append("## 1. Baseline PPL sweep (ctx=4096, n_chunks=40)")
        out.append("")
        out.append("| codec | PPL | ΔPPL vs f16/f16 | wall-clock |")
        out.append("|---|---|---|---|")
        base_ppl = next((r["final_ppl"] for r in sweep if r["k_type"] == "f16" and r["v_type"] == "f16"), None)
        for r in sweep:
            ppl = r.get("final_ppl")
            elapsed = r.get("elapsed_s", 0)
            if ppl is None:
                out.append(f"| {r['label']} | (failed) | — | {elapsed:.0f}s |")
                continue
            d = (ppl - base_ppl) / base_ppl * 100 if base_ppl else 0
            out.append(f"| {r['label']} | {ppl:.4f} | {d:+.2f}% | {elapsed:.0f}s |")
        out.append("")

    # ── KL divergence ───────────────────────────────────────────────
    kld = load_json(args.results_dir / "kld_c4k_n20.json")
    if kld:
        out.append("## 2. KL divergence vs f16/f16 baseline (ctx=4096, n_chunks=20)")
        out.append("")
        out.append("| codec | mean | median | 95% | 99% | 99.9% | max | same-top% |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in kld:
            m = r.get("metrics", {})
            def fmt(v):
                if v is None: return "—"
                if abs(v) >= 100: return f"{v:.2f}"
                return f"{v:.4f}"
            out.append(f"| {r['label']} | {fmt(m.get('mean_kld'))} | {fmt(m.get('median_kld'))} | "
                       f"{fmt(m.get('kld_95_0'))} | {fmt(m.get('kld_99_0'))} | "
                       f"{fmt(m.get('kld_99_9'))} | {fmt(m.get('max_kld'))} | "
                       f"{fmt(m.get('same_top_pct'))}% |")
        out.append("")
        out.append("Heavy-tail check: ratio of max_kld to median_kld")
        out.append("")
        out.append("| codec | max/median | heavy-tailed? |")
        out.append("|---|---|---|")
        for r in kld:
            m = r.get("metrics", {})
            mx = m.get("max_kld")
            med = m.get("median_kld")
            if mx and med and med > 0:
                ratio = mx / med
                tag = "**YES** (sink/recency may help)" if ratio > 100 else "no (uniform)"
                out.append(f"| {r['label']} | {ratio:.0f}× | {tag} |")
            else:
                out.append(f"| {r['label']} | — | — |")
        out.append("")

    # ── Recency-position split ──────────────────────────────────────
    rps = load_json(args.results_dir / "recency_position_split.json")
    if rps:
        out.append("## 3. PPL vs context length (recency hypothesis test)")
        out.append("")
        codecs = sorted(set(r["codec"] for r in rps))
        ctxs = sorted(set(r["ctx"] for r in rps))
        out.append("PPL:")
        out.append("")
        out.append(f"| codec | " + " | ".join(f"ctx={c}" for c in ctxs) + " |")
        out.append("|---|" + "---|" * len(ctxs))
        for codec in codecs:
            row = [codec]
            for ctx in ctxs:
                r = next((x for x in rps if x["codec"] == codec and x["ctx"] == ctx), None)
                row.append(f"{r['final_ppl']:.4f}" if r and r["final_ppl"] else "—")
            out.append("| " + " | ".join(row) + " |")
        out.append("")
        base_rps = [r for r in rps if r["codec"] == "f16/f16"]
        if base_rps:
            out.append("ΔPPL vs f16/f16:")
            out.append("")
            out.append(f"| codec | " + " | ".join(f"ctx={c}" for c in ctxs) + " |")
            out.append("|---|" + "---|" * len(ctxs))
            for codec in codecs:
                if codec == "f16/f16": continue
                row = [codec]
                for ctx in ctxs:
                    rb = next((x for x in rps if x["codec"] == "f16/f16" and x["ctx"] == ctx and x["final_ppl"]), None)
                    ro = next((x for x in rps if x["codec"] == codec and x["ctx"] == ctx and x["final_ppl"]), None)
                    if rb and ro:
                        d = (ro["final_ppl"] - rb["final_ppl"]) / rb["final_ppl"] * 100
                        row.append(f"{d:+.2f}%")
                    else:
                        row.append("—")
                out.append("| " + " | ".join(row) + " |")
            out.append("")
            out.append("**Interpretation:** if ΔPPL grows monotonically with ctx, "
                       "compression error accumulates with context length → recency window would help. "
                       "If ΔPPL is flat across ctx, the error is per-token, not context-dependent → "
                       "recency window unlikely to help.")
            out.append("")

    # ── NIAH ────────────────────────────────────────────────────────
    niah = load_json(args.results_dir / "niah.json")
    if niah:
        out.append("## 4. NIAH retrieval accuracy")
        out.append("")
        codecs = sorted(set((r["k_type"], r["v_type"]) for r in niah))
        ctxs = sorted(set(r["ctx"] for r in niah))
        out.append("Accuracy (correct / total) by codec × ctx:")
        out.append("")
        out.append(f"| codec | " + " | ".join(f"ctx={c}" for c in ctxs) + " |")
        out.append("|---|" + "---|" * len(ctxs))
        for k, v in codecs:
            row = [f"{k}/{v}"]
            for ctx in ctxs:
                rs = [r for r in niah if r["k_type"] == k and r["v_type"] == v and r["ctx"] == ctx]
                if rs:
                    correct = sum(r["correct"] for r in rs)
                    row.append(f"{correct}/{len(rs)}")
                else:
                    row.append("—")
            out.append("| " + " | ".join(row) + " |")
        out.append("")

        depths = sorted(set(r["depth_pct"] for r in niah))
        if "q8_0" in [k for k, v in codecs] and "turbo3" in [v for k, v in codecs]:
            out.append("q8/turbo3 per-depth breakdown:")
            out.append("")
            out.append(f"| ctx | " + " | ".join(f"d={int(d*100)}%" for d in depths) + " |")
            out.append("|---|" + "---|" * len(depths))
            for ctx in ctxs:
                row = [str(ctx)]
                for d in depths:
                    r = next((x for x in niah if x["k_type"] == "q8_0" and x["v_type"] == "turbo3"
                              and x["ctx"] == ctx and abs(x["depth_pct"] - d) < 1e-3), None)
                    if r is None:
                        row.append("—")
                    else:
                        row.append("✓" if r["correct"] else "✗")
                out.append("| " + " | ".join(row) + " |")
            out.append("")

    # ── Verdict ─────────────────────────────────────────────────────
    out.append("## Verdict")
    out.append("")
    out.append("[Manual analysis of the above tables — see READERS_DIGEST.md for the full writeup]")
    out.append("")

    args.out.write_text("\n".join(out))
    print(f"Wrote summary to {args.out}")
    print("\n".join(out[:80]))  # preview


if __name__ == "__main__":
    main()
